<?php

namespace ContainerKNGu4y1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BcmCAbnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BcmCAbn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BcmCAbn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tasks' => ['privates', '.errored..service_locator.BcmCAbn.App\\Entity\\Tasks', NULL, 'Cannot autowire service ".service_locator.BcmCAbn": it needs an instance of "App\\Entity\\Tasks" but this type has been excluded in "config/services.yaml".'],
            'tasksRepository' => ['privates', 'App\\Repository\\TasksRepository', 'getTasksRepositoryService', true],
        ], [
            'tasks' => 'App\\Entity\\Tasks',
            'tasksRepository' => 'App\\Repository\\TasksRepository',
        ]);
    }
}
