<?php

namespace ContainerKNGu4y1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KGfzNlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kGfz_Nl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kGfz_Nl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'task' => ['privates', '.errored..service_locator.kGfz_Nl.App\\Entity\\Tasks', NULL, 'Cannot autowire service ".service_locator.kGfz_Nl": it needs an instance of "App\\Entity\\Tasks" but this type has been excluded in "config/services.yaml".'],
        ], [
            'task' => 'App\\Entity\\Tasks',
        ]);
    }
}
