<?php

namespace ContainerKNGu4y1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTasks3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.kGfz_Nl.App\Entity\Tasks' shared service.
     *
     * @return \App\Entity\Tasks
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.kGfz_Nl": it needs an instance of "App\\Entity\\Tasks" but this type has been excluded in "config/services.yaml".');
    }
}
