<?php

namespace Container8sedn0q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjets2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.z.K9IPV.App\Entity\Projets' shared service.
     *
     * @return \App\Entity\Projets
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.z.K9IPV": it needs an instance of "App\\Entity\\Projets" but this type has been excluded in "config/services.yaml".');
    }
}
