<?php

namespace ContainerNVkIT0i;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G7bzEafService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.g7bzEaf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.g7bzEaf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\ProjetsController::delete' => ['privates', '.service_locator.gN03bWF', 'get_ServiceLocator_GN03bWFService', true],
            'App\\Controller\\ProjetsController::edit' => ['privates', '.service_locator.gN03bWF', 'get_ServiceLocator_GN03bWFService', true],
            'App\\Controller\\ProjetsController::index' => ['privates', '.service_locator.m5ZkXH.', 'get_ServiceLocator_M5ZkXH_Service', true],
            'App\\Controller\\ProjetsController::new' => ['privates', '.service_locator.m5ZkXH.', 'get_ServiceLocator_M5ZkXH_Service', true],
            'App\\Controller\\ProjetsController::show' => ['privates', '.service_locator.z.K9IPV', 'get_ServiceLocator_Z_K9IPVService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\TasksController::delete' => ['privates', '.service_locator.GbpbeNv', 'get_ServiceLocator_GbpbeNvService', true],
            'App\\Controller\\TasksController::done' => ['privates', '.service_locator.GbpbeNv', 'get_ServiceLocator_GbpbeNvService', true],
            'App\\Controller\\TasksController::edit' => ['privates', '.service_locator.GbpbeNv', 'get_ServiceLocator_GbpbeNvService', true],
            'App\\Controller\\TasksController::inProgress' => ['privates', '.service_locator.GbpbeNv', 'get_ServiceLocator_GbpbeNvService', true],
            'App\\Controller\\TasksController::index' => ['privates', '.service_locator.wawYoyW', 'get_ServiceLocator_WawYoyWService', true],
            'App\\Controller\\TasksController::indexDone' => ['privates', '.service_locator.Q1tLaJm', 'get_ServiceLocator_Q1tLaJmService', true],
            'App\\Controller\\TasksController::new' => ['privates', '.service_locator.wawYoyW', 'get_ServiceLocator_WawYoyWService', true],
            'App\\Controller\\TasksController::show' => ['privates', '.service_locator.kGfz_Nl', 'get_ServiceLocator_KGfzNlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ProjetsController:delete' => ['privates', '.service_locator.gN03bWF', 'get_ServiceLocator_GN03bWFService', true],
            'App\\Controller\\ProjetsController:edit' => ['privates', '.service_locator.gN03bWF', 'get_ServiceLocator_GN03bWFService', true],
            'App\\Controller\\ProjetsController:index' => ['privates', '.service_locator.m5ZkXH.', 'get_ServiceLocator_M5ZkXH_Service', true],
            'App\\Controller\\ProjetsController:new' => ['privates', '.service_locator.m5ZkXH.', 'get_ServiceLocator_M5ZkXH_Service', true],
            'App\\Controller\\ProjetsController:show' => ['privates', '.service_locator.z.K9IPV', 'get_ServiceLocator_Z_K9IPVService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\TasksController:delete' => ['privates', '.service_locator.GbpbeNv', 'get_ServiceLocator_GbpbeNvService', true],
            'App\\Controller\\TasksController:done' => ['privates', '.service_locator.GbpbeNv', 'get_ServiceLocator_GbpbeNvService', true],
            'App\\Controller\\TasksController:edit' => ['privates', '.service_locator.GbpbeNv', 'get_ServiceLocator_GbpbeNvService', true],
            'App\\Controller\\TasksController:inProgress' => ['privates', '.service_locator.GbpbeNv', 'get_ServiceLocator_GbpbeNvService', true],
            'App\\Controller\\TasksController:index' => ['privates', '.service_locator.wawYoyW', 'get_ServiceLocator_WawYoyWService', true],
            'App\\Controller\\TasksController:indexDone' => ['privates', '.service_locator.Q1tLaJm', 'get_ServiceLocator_Q1tLaJmService', true],
            'App\\Controller\\TasksController:new' => ['privates', '.service_locator.wawYoyW', 'get_ServiceLocator_WawYoyWService', true],
            'App\\Controller\\TasksController:show' => ['privates', '.service_locator.kGfz_Nl', 'get_ServiceLocator_KGfzNlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ProjetsController::delete' => '?',
            'App\\Controller\\ProjetsController::edit' => '?',
            'App\\Controller\\ProjetsController::index' => '?',
            'App\\Controller\\ProjetsController::new' => '?',
            'App\\Controller\\ProjetsController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\TasksController::delete' => '?',
            'App\\Controller\\TasksController::done' => '?',
            'App\\Controller\\TasksController::edit' => '?',
            'App\\Controller\\TasksController::inProgress' => '?',
            'App\\Controller\\TasksController::index' => '?',
            'App\\Controller\\TasksController::indexDone' => '?',
            'App\\Controller\\TasksController::new' => '?',
            'App\\Controller\\TasksController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ProjetsController:delete' => '?',
            'App\\Controller\\ProjetsController:edit' => '?',
            'App\\Controller\\ProjetsController:index' => '?',
            'App\\Controller\\ProjetsController:new' => '?',
            'App\\Controller\\ProjetsController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\TasksController:delete' => '?',
            'App\\Controller\\TasksController:done' => '?',
            'App\\Controller\\TasksController:edit' => '?',
            'App\\Controller\\TasksController:inProgress' => '?',
            'App\\Controller\\TasksController:index' => '?',
            'App\\Controller\\TasksController:indexDone' => '?',
            'App\\Controller\\TasksController:new' => '?',
            'App\\Controller\\TasksController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
