<?php

namespace ContainerNVkIT0i;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GN03bWFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gN03bWF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gN03bWF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'projet' => ['privates', '.errored..service_locator.gN03bWF.App\\Entity\\Projets', NULL, 'Cannot autowire service ".service_locator.gN03bWF": it needs an instance of "App\\Entity\\Projets" but this type has been excluded in "config/services.yaml".'],
            'projetsRepository' => ['privates', 'App\\Repository\\ProjetsRepository', 'getProjetsRepositoryService', true],
        ], [
            'projet' => 'App\\Entity\\Projets',
            'projetsRepository' => 'App\\Repository\\ProjetsRepository',
        ]);
    }
}
