<?php

namespace ContainerYrtY5xR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M5ZkXH_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.m5ZkXH.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.m5ZkXH.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'projetsRepository' => ['privates', 'App\\Repository\\ProjetsRepository', 'getProjetsRepositoryService', true],
        ], [
            'projetsRepository' => 'App\\Repository\\ProjetsRepository',
        ]);
    }
}
